### PR TITLE
format payment-encryption.md

### PR DESCRIPTION
**Pull request by wanli**
format https://w3c.github.io/webpayments-methods-tokenization/ based on the example of https://w3c.github.io/webpayments-methods-tokenization/

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
@wanli can you explain this change briefly, the description above doesn't make much sense (_format **X** based on the example of **X**_)

**Comment by ianbjacobs** [comment]
I believe @wanli is referring to this document:
 https://github.com/w3c/webpayments-crypto/blob/master/payment-encryption.md

Ian

**Comment by ianbjacobs** [comment]
@wanli, I want to apologize. I think we did not sufficiently chat about how to translate the wiki text in a respect document. I am happy to take a pass at your edits as a respec source.

**Comment by ianbjacobs** [comment]
I have created a respec version of the document, see:
 https://w3c.github.io/webpayments-crypto/

**Comment by wanli** [comment]
thank you @ianbjacobs 

@adrianhopebailie sorry about the description.

**Comment by adrianhopebailie** [comment]
Np, thanks for context @ianbjacobs (and the conversion)

**Pull request closed without merging**
